services:
  js-react-example:
    image: infinum-js-react-example
    container_name: infinum-js-react-example
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - ./.env.local
    ports:
      - '3000:3000'
