packages:
  - apps/*
  - packages/*

catalog:
  '@actions/core': 1.11.1
  '@changesets/cli': 2.29.5
  '@eslint/compat': 1.3.1
  '@eslint/js': 9.31.0
  '@next/bundle-analyzer': 15.4.4
  '@next/env': 15.4.4
  '@next/eslint-plugin-next': 15.4.4
  '@radix-ui/react-label': 2.1.7
  '@radix-ui/react-select': 2.2.5
  '@radix-ui/react-slot': 1.2.3
  '@radix-ui/react-tooltip': 1.2.7
  '@storybook/addon-a11y': 9.0.18
  '@storybook/addon-designs': 10.0.2
  '@storybook/addon-docs': 9.0.18
  '@storybook/addon-themes': 9.0.18
  '@storybook/nextjs': 9.0.18
  '@tailwindcss/postcss': 4.1.11
  '@testing-library/dom': 10.4.0
  '@testing-library/jest-dom': 6.6.3
  '@testing-library/react': 16.3.0
  '@testing-library/user-event': 14.6.1
  '@types/jest': 30.0.0
  '@types/node': 24.1.0
  '@types/react': 19.1.8
  '@types/react-dom': 19.1.6
  '@typescript-eslint/eslint-plugin': 8.38.0
  autoprefixer: 10.4.21
  class-variance-authority: 0.7.1
  clsx: 2.1.1
  envsafe: 2.0.3
  eslint: 9.31.0
  eslint-config-prettier: 10.1.8
  eslint-plugin-jest: 29.0.1
  eslint-plugin-prettier: 5.5.3
  eslint-plugin-react: 7.37.5
  eslint-plugin-react-hooks: 5.2.0
  eslint-plugin-storybook: 9.0.18
  globals: 16.3.0
  husky: 9.1.7
  jest: 30.0.5
  jest-environment-jsdom: 30.0.5
  license-checker-rseidelsohn: 4.4.2
  lint-staged: 16.1.2
  lucide-react: 0.525.0
  next: 15.4.4
  next-auth: 4.24.11
  next-intl: 4.3.4
  next-runtime-env: 3.3.0
  next-themes: 0.4.6
  postcss: 8.5.6
  prettier: 3.6.2
  prettier-plugin-sh: 0.18.0
  prettier-plugin-tailwindcss: 0.6.14
  react: 19.1.0
  react-dom: 19.1.0
  remark: 15.0.1
  remark-cli: 12.0.1
  shadcn: 2.9.3
  storybook: 9.0.18
  tailwind-merge: 3.3.1
  tailwindcss: 4.1.11
  ts-jest: 29.4.0
  ts-node: 10.9.2
  turbo: 2.5.5
  tw-animate-css: 1.3.6
  typescript: 5.8.3
  typescript-eslint: 8.38.0

engineStrict: true

minimumReleaseAge: 2880

onlyBuiltDependencies:
  - '@tailwindcss/oxide@4.1.11'
  - core-js-pure@3.44.0
  - esbuild@0.25.8
  - msw@2.10.4
  - sharp@0.34.3
  - unrs-resolver@1.11.1

peerDependencyRules:
  allowedVersions:
    next-runtime-env>next: '>=14 <16'
    next-runtime-env>react: '>=18 <20'

strictDepBuilds: true

strictPeerDependencies: true
