packages:
  - apps/*
  - packages/*

catalog:
  '@actions/core': 1.11.1
  '@changesets/cli': 2.29.7
  '@eslint/compat': 1.4.1
  '@eslint/js': 9.39.0
  '@next/bundle-analyzer': 16.0.1
  '@next/env': 16.0.1
  '@next/eslint-plugin-next': 16.0.1
  '@radix-ui/react-label': 2.1.7
  '@radix-ui/react-select': 2.2.6
  '@radix-ui/react-slot': 1.2.3
  '@radix-ui/react-tooltip': 1.2.8
  '@storybook/addon-a11y': 10.0.3
  '@storybook/addon-designs': 11.0.1
  '@storybook/addon-docs': 10.0.3
  '@storybook/addon-themes': 10.0.3
  '@storybook/nextjs': 10.0.3
  '@tailwindcss/postcss': 4.1.16
  '@testing-library/dom': 10.4.1
  '@testing-library/jest-dom': 6.9.1
  '@testing-library/react': 16.3.0
  '@testing-library/user-event': 14.6.1
  '@types/jest': 30.0.0
  '@types/node': 24.10.0
  '@types/react': 19.2.2
  '@types/react-dom': 19.2.2
  '@typescript-eslint/eslint-plugin': 8.46.2
  autoprefixer: 10.4.21
  class-variance-authority: 0.7.1
  clsx: 2.1.1
  envsafe: 2.0.3
  eslint: 9.39.0
  eslint-config-prettier: 10.1.8
  eslint-plugin-jest: 29.0.1
  eslint-plugin-prettier: 5.5.4
  eslint-plugin-react: 7.37.5
  eslint-plugin-react-hooks: 7.0.1
  eslint-plugin-storybook: 10.0.3
  globals: 16.5.0
  husky: 9.1.7
  jest: 30.2.0
  jest-environment-jsdom: 30.2.0
  license-checker-rseidelsohn: 4.4.2
  lint-staged: 16.2.6
  lucide-react: 0.552.0
  next: 16.0.1
  next-auth: 4.24.13
  next-intl: 4.4.0
  next-themes: 0.4.6
  postcss: 8.5.6
  prettier: 3.6.2
  prettier-plugin-sh: 0.18.0
  prettier-plugin-tailwindcss: 0.7.1
  react: 19.2.0
  react-dom: 19.2.0
  remark: 15.0.1
  remark-cli: 12.0.1
  shadcn: 3.5.0
  storybook: 10.0.3
  tailwind-merge: 3.3.1
  tailwindcss: 4.1.16
  ts-jest: 29.4.5
  ts-node: 10.9.2
  turbo: 2.6.0
  tw-animate-css: 1.4.0
  typescript: 5.8.3
  typescript-eslint: 8.46.2

engineStrict: true

minimumReleaseAge: 2880

onlyBuiltDependencies:
  - '@tailwindcss/oxide@4.1.11'
  - core-js-pure@3.44.0
  - esbuild@0.25.8
  - msw@2.10.4
  - sharp@0.34.4
  - unrs-resolver@1.11.1

strictDepBuilds: true

strictPeerDependencies: true
