[settings]
lockfile = true
install_before = "7d"
idiomatic_version_file_enable_tools = ["node", "pnpm"]
env_shell_expand = false

[tasks.dev]
run = "pnpm run _dev"
env = {
	NEXTAUTH_SECRET = "{{exec(command='op read \"op://JS general/ReactExample/NextAuthSecret\"')}}",
	TEST_SECRET = "{{exec(command='op read \"op://JS general/ReactExample/TestSecret\"')}}"
}

[tasks.build]
run = "pnpm run _build"
env = {
	NEXTAUTH_SECRET = "{{exec(command='op read \"op://JS general/ReactExample/NextAuthSecret\"')}}",
	TEST_SECRET = "{{exec(command='op read \"op://JS general/ReactExample/TestSecret\"')}}"
}

[tasks.start]
run = "pnpm run _start"
env = {
	NEXTAUTH_SECRET = "{{exec(command='op read \"op://JS general/ReactExample/NextAuthSecret\"')}}",
	TEST_SECRET = "{{exec(command='op read \"op://JS general/ReactExample/TestSecret\"')}}"
}

[env]
_.file = ".env.local"
