name: 👁️‍🗨️ Code Analysis
description: 'Run code analysis'

runs:
  using: 'composite'
  steps:
    - name: 🧐 Check with Prettier
      run: pnpm prettier:check
      shell: bash

    - name: 🫣 Lint
      run: pnpm lint
      shell: bash
