name: Deploy staging

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy
    uses: infinum/js-pipeline/.github/workflows/build.yml@v1
    with:
      ci_steps: 'deploy-next-ssr'
      features: 'secrets'
      secrets: 'js-react-example'
      deploy_host: 'react-example.byinfinum.co'
      deploy_user: 'js_react_example'
      environment: 'staging'
    secrets:
      SSH_PRIVATE_KEY: ${{ secrets.STAGING_KEY }}