name: Deploy staging

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy
    uses: infinum/js-pipeline/.github/workflows/pipeline.yml@master
    with:
      ci_steps: 'deploy'
      features: 'secrets'
      secrets: 'js-react-example'
      deploy_host: 'react-example.byinfinum.co'
      deploy_user: 'js_react_example'
      environment: 'staging'
      deploy_port: '229'
    secrets:
      SSH_PRIVATE_KEY: ${{ secrets.STAGING_KEY }}
      VAULT_ADDR: ${{ secrets.VAULT_ADDR }}
      VAULT_AUTH_METHOD: ${{ secrets.VAULT_AUTH_METHOD }}
      VAULT_AUTH_ROLE_ID: ${{ secrets.VAULT_AUTH_ROLE_ID }}
      VAULT_AUTH_SECRET_ID: ${{ secrets.VAULT_AUTH_SECRET_ID }}