name: Build

on:
  pull_request:

jobs:
  test-analyze:
    name: 'Run'
    uses: infinum/js-pipeline/.github/workflows/pipeline.yml@main
    with:
      ci_steps: 'lint test'
      workflow: '.github/workflows/pr.yml'
      environment: 'staging'
